name: json_placeholder_retrofit
description: A Flutter project to demonstrate rest api call from jsonplaceholder.typicode.com using
  retrofit package and json_annotation package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  retrofit: ^3.0.1+1
  dio: ^4.0.4
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.5


flutter:
  uses-material-design: true